### ISSUE TITLE
Windows 11 Crash on Start

### ISSUE THREAD

**Issue by WhiteNoiseDev** [dankrusi/WindowsVirtualDesktopHelper#1]
I was just looking for something like this.
Sadly, It crashes on start. Not sure how I can help you debug this. Win 11 22H2

![image](https://user-images.githubusercontent.com/3163647/202057674-a1b56d04-2a8d-4ba1-a55d-6dca69b7c644.png)

**Comment by dankrusi** [comment]
Sorry about this. What Windows version are you on? Is there any way you can start the app from the command line and let me know the error details? Thanks

**Comment by dankrusi** [comment]
I just published v1.1 that fixes the Windows11 detection. Can you try that?

**Comment by WhiteNoiseDev** [comment]
Still the same, it crashes. 
There is no output if I run the program from console.

**Comment by dankrusi** [comment]
Do you have .NET installed?

**Comment by WhiteNoiseDev** [comment]
I think I do. Can you send me a link to a runtime that you know works?

**Comment by WhiteNoiseDev** [comment]
```
❯ dotnet --list-runtimes
Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by WhiteNoiseDev** [comment]
![image](https://user-images.githubusercontent.com/3163647/202245986-20561620-4401-4a6f-ab5b-903b3f321bf6.png)

![image](https://user-images.githubusercontent.com/3163647/202246013-75b725e6-ae7b-4cb1-9204-abc25cc858ee.png)

**Comment by dankrusi** [comment]
Thanks, .NET seems to installed. However the error code 0xe0434352 can be related to:

Unknown software exception (0xe0434352) is an error that is related to .NET installation. The majority of the reasons for this error is having a faulty .NET Framework, another reason is because of some corrupted files or old drivers that are contradicting with Windows.

See https://www.microsoft.com/en-gb/download/details.aspx?id=30135 maybe? Otherwise try a clean installation of .NET. The recommended version from https://dotnet.microsoft.com/en-us/download/dotnet-framework should be fine.

Best

**Comment by WhiteNoiseDev** [comment]
I rechecked and I have 4.8.1 installed and managed by the OS. I tried to run the repair software but it didn't change anything. I don't think that this is the issue.

**Comment by dankrusi** [comment]
So wierd, thanks for your efforts. You're a programmer right? Want to debug the application? Its a very simple C# app and should be really easy to compile and test... 

One final test you can do with the .exe is see if admin rights helps, though I don't think it should make a difference. The Virtual Desktop API form windows keeps changing over Win 10 and Win 11, and has even changed in between. However Win 11 22H2 it should work, as this is the version I have tested successfully.

If you can get one of these https://github.com/MScholtes/VirtualDesktop to work, you can let me know I can further analyse and debug the situation.

Best

**Comment by souradeep100** [comment]
getting the same problem.
`Application: WindowsVirtualDesktopHelper.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at VirtualDesktopIndicator.Native.VirtualDesktop.Implementation.VirtualDesktopWin11+IVirtualDesktopManagerInternal.GetDesktops(IntPtr, IObjectArray ByRef)
   at VirtualDesktopIndicator.Native.VirtualDesktop.Implementation.VirtualDesktopWin11+DesktopManager.GetDesktopIndex(IVirtualDesktop)
   at VirtualDesktopIndicator.Native.VirtualDesktop.Implementation.VirtualDesktopWin11.DesktopNameFromDesktop(IVirtualDesktop)
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(System.String[])

`

**Comment by dankrusi** [comment]
Hi,

Sorry for your troubles. I'd really like to resolve this issue, but I will need everyones help as I can't reproduce it on any Windows 11 installation I have.

The latest version 1.3 includes a mimimal error info and bug reporting UI:

![image](https://user-images.githubusercontent.com/190233/204482791-4cfb4c6f-cf31-4012-aec8-e871b1bb82e6.png)

Can you try this and copy the info that is reported? If this window never shows up, then it must be an issue with .NET and we can try using a newer version of .NET.

Thanks!

**Comment by dankrusi** [comment]
Thanks @WhiteNoiseDev. I see you are on Windows Insider right? Does this version work for you?
[WindowsVirtualDesktopHelper.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/10114730/WindowsVirtualDesktopHelper.zip)

**Comment by WhiteNoiseDev** [comment]
No, I am not insiders.

Still error
```
LoadVDDisplayInfo: could not get current display number: GetVDDisplayNumber: could not get current display number: A null reference pointer was passed to the stub. (Exception from HRESULT: 0x800706F4)
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

GetVDDisplayNumber: could not get current display number: A null reference pointer was passed to the stub. (Exception from HRESULT: 0x800706F4)
   at WindowsVirtualDesktopHelper.App.GetVDDisplayNumber(Boolean throwException)
   at WindowsVirtualDesktopHelper.App.LoadVDDisplayInfo()

Windows Build: 22621
```

**Comment by dankrusi** [comment]
@WhiteNoiseDev hmmm thanks. We know now that it definately has todo with the Windows API. Do any of these exes work for you?
[mscholtes-VirtualDesktopCommandLine.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/10120802/mscholtes-VirtualDesktopCommandLine.zip)
You can try from command line with parameter /List. In the mean time I am trying to get the same version of Windows.
Thanks

**Comment by dankrusi** [comment]
Hi @WhiteNoiseDev,

I was able to get Windows 22H2, and managed to fix this issue. Please use v1.4, that should work for you.

Best,

-dan

**Comment by dankrusi** [comment]
@souradeep100, most likely your error was the same issue. Give v1.4 a try.

**Comment by WhiteNoiseDev** [comment]
I can confirm that this works! It pairs well with this AHK script <https://github.com/pmb6tz/windows-desktop-switcher>
